STAGE_MARKERS = {
    "wheat": [
        {
            "label": "Seeding",
            "start_month": 9,
            "start_day": 1,
            "year_offset": -1,
            "dry_warn": -0.4,
            "dry_critical": -0.8,
            "wet_warn": 0.6,
            "wet_critical": 1,
            "color": "#6c757d",
        },
        {
            "label": "Dormancy",
            "start_month": 12,
            "start_day": 1,
            "year_offset": -1,
            "dry_warn": -0.8,
            "dry_critical": -1.2,
            "wet_warn": 1.0,
            "wet_critical": 1.6,
            "color": "#6c757d",
        },
        {
            "label": "Growth",
            "start_month": 2,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.5,
            "dry_critical": -1.0,
            "wet_warn": 0.8,
            "wet_critical": 1.4,
            "color": "#6c757d",
        },
        {
            "label": "Flowering",
            "start_month": 4,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.3,
            "dry_critical": -0.6,
            "wet_warn": 0.8,
            "wet_critical": 1.4,
            "color": "#6c757d",
        },
        {
            "label": "Grain filling",
            "start_month": 5,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.5,
            "dry_critical": -1.0,
            "wet_warn": 0.8,
            "wet_critical": 1.4,
            "color": "#6c757d",
        },
        {
            "label": "Harvest",
            "start_month": 7,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -1.0,
            "dry_critical": -1.5,
            "wet_warn": 0.6,
            "wet_critical": 1.0,
            "color": "#6c757d",
        },
    ],
    "bilberry": [
        {
            "label": "Dormancy",
            "start_month": 11,
            "start_day": 1,
            "year_offset": -1,
            "dry_warn": -0.8,
            "dry_critical": -1.2,
            "wet_warn": 1.0,
            "wet_critical": 1.6,
            "color": "#6c757d",
        },
        {
            "label": "Bud Swelling \n& Leaf Emergence",
            "start_month": 3,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.3,
            "dry_critical": -1.0,
            "wet_warn": 0.6,
            "wet_critical": 1.0,
            "color": "#6c757d",
        },
        {
            "label": "Flowering",
            "start_month": 4,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.2,
            "dry_critical": -0.8,
            "wet_warn": 0.6,
            "wet_critical": 1.0,
            "color": "#6c757d",
        },
        {
            "label": "Fruit set",
            "start_month": 5,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.3,
            "dry_critical": -0.9,
            "wet_warn": 0.6,
            "wet_critical": 1.0,
            "color": "#6c757d",
        },
        {
            "label": "Berry growth & Ripening",
            "start_month": 6,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.5,
            "dry_critical": -1.0,
            "wet_warn": 0.6,
            "wet_critical": 1.0,
            "color": "#6c757d",
        },
        {
            "label": "Harvest",
            "start_month": 7,
            "start_day": 15,
            "year_offset": 0,
            "dry_warn": -0.3,
            "dry_critical": -0.8,
            "wet_warn": 0.6,
            "wet_critical": 1.0,
            "color": "#6c757d",
        },
        {
            "label": "Leaf Senescence",
            "start_month": 9,
            "start_day": 1,
            "year_offset": 0,
            "dry_warn": -0.5,
            "dry_critical": -1.2,
            "wet_warn": 0.6,
            "wet_critical": 1.0,
            "color": "#6c757d",
        },
    ],
}
