STAGE_MARKERS = [
    {
        "label": "Seeding",
        "start_month": 9,
        "start_day": 1,
        "year_offset": -1,
        "warn_temp": 28,
        "alert_temp": 32,
        "low_temp": 6,
        "color": "#6c757d",
    },
    {
        "label": "Dormancy",
        "start_month": 12,
        "start_day": 1,
        "year_offset": -1,
        "color": "#6c757d",
        "warn_temp": 12,
        "alert_temp": 15,
        "low_temp": 0,
    },
    {
        "label": "Growth",
        "start_month": 2,
        "start_day": 1,
        "year_offset": 0,
        "warn_temp": 30,
        "alert_temp": 34,
        "low_temp": 8,
        "color": "#6c757d",
    },
    {
        "label": "Flowering",
        "start_month": 4,
        "start_day": 1,
        "year_offset": 0,
        "warn_temp": 28,
        "alert_temp": 30,
        "low_temp": 12,
        "color": "#6c757d",
    },
    {
        "label": "Grain filling",
        "start_month": 5,
        "start_day": 1,
        "year_offset": 0,
        "warn_temp": 30,
        "alert_temp": 35,
        "low_temp": 14,
        "color": "#6c757d",
    },
    {
        "label": "Harvest",
        "start_month": 7,
        "start_day": 1,
        "year_offset": 0,
        "warn_temp": 32,
        "alert_temp": 36,
        "low_temp": 12,
        "color": "#6c757d",
    },
]